README.md
[Slack context](https://ifttt.slack.com/archives/C1JHG6HDF/p1574090194145500?thread_ts=1573738213.131200&cid=C1JHG6HDF)
=> Clear up userToken confusion

Examples/Podfile.lock, Examples/Pods/Local Podspecs/IFTTTConnectSDK.podspec.json, Examples/Pods/Manifest.lock, Examples/Pods/Target Support Files/IFTTTConnectSDK/ResourceBundle-IFTTTConnectSDK-IFTTTConnectSDK-Info.plist, IFTTT SDK/ConnectButton+Constants.swift, IFTTT SDK/ConnectButton+LabelAnimator.swift, IFTTT SDK/ConnectButton.swift, IFTTT SDK/Info.plist
- Updating pod version of grocery express
- Fixing line showing up on connect button
- Fixing spacing of "Connect" label
=> Button UI Fixes

IFTTT SDK/Analytics.swift, IFTTT SDK/ConnectButtonController.swift
- Allowing for disconnect on tap of the button knob
- Allowing for disconnect on tap within the button
- Turning off analytics logging
=>  Disconnect tap updates and turning off analytics logging

IFTTT SDK/AboutViewController.swift
Navigating to IFTTT app or web page after tapping on service icons on about page
=> About page icon navigation

IFTTT SDK/AboutViewController.swift, IFTTT SDK/Localizable.strings
Changing copy on deeplink button and adding logic to open connection page in either web or IFTTT app
=> About page updates

README.md
@ssathy2 would love some help filling in the disable tracking section.
=> Update README to include tracking section

IFTTT SDK/ConnectButton.swift, IFTTT SDK/ConnectButtonController.swift
- Fixing email impression events not getting sent. 
- Removing unneeded display delegate
=> Analytics fixes

IFTTT SDK/Connection+parsing.swift, IFTTT SDK/Connection.swift
- Adding logic to parse features of Connection from network response
- Adding deprecation notice in code for usage of `valuePropositions`
=> Deprecating valuePropositions of Connection

IFTTT SDK/AuthenticationSession.swift, IFTTT SDK/ConnectionVerificationSession.swift
Updating authentication session to pass in a boolean for controlling ephermeral sessions
=> Ephemeral authentication session support

Examples/GroceryExpress/ConnectionViewController.swift, Examples/GroceryExpress/Main.storyboard, Examples/GroceryExpress/Settings.swift, Examples/GroceryExpress/SettingsViewController.swift, IFTTT SDK/ConnectButtonController.swift, IFTTT SDK/ConnectionActivationFlow.swift, IFTTT SDK/ConnectionConfiguration.swift
- Adding ability to skip connection configuration in the web and IFTTT app flow
- Added toggle to Grocery Express to skip configuration
=> Connection configuration skipping

Examples/GroceryExpress/ConnectionViewController.swift
Use value from settings to determine whether or not to skip config in grocery express
=> Grocery express optional config bugfix

IFTTT SDK.xcodeproj/project.pbxproj, IFTTT SDK/ConnectButtonController.swift, IFTTTConnectSDK.podspec
=> Adding language strings files to project for Carthage compatability

Examples/GroceryExpress/AppDelegate.swift, Examples/GroceryExpress/SettingsViewController.swift, IFTTT SDK/ConnectionsMonitor.swift, IFTTT SDK/ConnectionsRegistry.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/LocationService.swift, IFTTT SDK/PermissionsRequestor.swift, IFTTT SDK/RegionEventsRegistry.swift, IFTTT SDK/SynchronizationScheduler.swift, IFTTT SDK/SynchronizationSubscriber.swift, IFTTTConnectSDK.podspec, README.md
- Adding update method to allow SDK to manually force a synchronization 
- Cleanup and bugfixes
=> Manual synchronization method

Examples/GroceryExpress/AppDelegate.swift, Examples/Pods/Pods.xcodeproj/project.pbxproj, IFTTT SDK.xcodeproj/project.pbxproj, IFTTT SDK/Analytics.swift, IFTTT SDK/CLCircularRegion+Parsing.swift, IFTTT SDK/ConnectButtonController+Logging.swift, IFTTT SDK/ConnectButtonController+Public.swift, IFTTT SDK/ConnectButtonController.swift, IFTTT SDK/Connection+Location.swift, IFTTT SDK/Connection+Parsing.swift, IFTTT SDK/Connection+Storage.swift, IFTTT SDK/Connection.swift, IFTTT SDK/ConnectionsMonitor.swift, IFTTT SDK/ConnectionsRegistry.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/LocalizedStrings.swift, IFTTT SDK/LocationService.swift, IFTTT SDK/NativeServices.swift, IFTTT SDK/PermissionsRequestor.swift, IFTTT SDK/SynchronizationManager.swift, IFTTT SDK/SynchronizationScheduler.swift, IFTTT SDK/SynchronizationSubscriber.swift, IFTTT SDKTests/Connection_ParsingTests.swift, IFTTT SDKTests/ConnectionsRegistryTests.swift, README.md
- Code cleanup
- Processing feature triggers so permission prompts can be shown sooner
- Readme update
=> Adding logging

IFTTT SDK/ConnectionsRegistry.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/LocationService.swift
- Fixes issue where region geofences might not get updated in a timely manner
=> Geofence registration timing fix

IFTTT SDK/Connection+Storage.swift, IFTTT SDK/ConnectionsMonitor.swift, IFTTT SDK/ConnectionsRegistry.swift, IFTTT SDK/ConnectionsSynchronizer.swift
Fixing an issue where geofences would not get de-registered properly upon connection deactivation
=> Geofence de-registration hotfix

.travis.yml, Examples/GroceryExpress/AppDelegate.swift, IFTTT SDK.xcodeproj/project.pbxproj, IFTTT SDK/CLCircularRegion+Parsing.swift, IFTTT SDK/ConnectButtonController+Public.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/Keychain.swift, IFTTT SDK/LocationService.swift, IFTTT SDK/RegionEventsRegistry.swift, IFTTT SDK/RegionsMonitor.swift, IFTTT SDK/SynchronizationManager.swift, IFTTT SDK/SynchronizationScheduler.swift, IFTTT SDK/SynchronizationSubscriber.swift, IFTTT SDKTests/Connection_ParsingTests.swift, IFTTT SDKTests/ConnectionsRegistryTests.swift, IFTTT SDKTests/RegionEventsRegistryTests.swift, IFTTT SDKTests/fetch_connection_response.json, Location.md
- Cleaning up code to support API rename. 
- Migrating tests for region events registry
=> Renaming APIs to better reflect usage of SDK

IFTTT SDK/ConnectionsMonitor.swift, IFTTT SDK/ConnectionsRegistry.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/RegionsMonitor.swift, SDKHostAppTests/ConnectionsRegistryTests.swift
- Fixes an issue where regions were still being monitored by the system even though synchronization was deactivated
=> Region monitoring fix

IFTTT SDK/AuthenticationSession.swift
Resolves https://github.com/IFTTT/ConnectSDK-iOS/issues/263.
=> Fixing deprecation and obseletion message in AuthenticationSession

Examples/Examples.xcodeproj/project.pbxproj, Examples/GroceryExpress/AddressSelectionViewController.swift, Examples/GroceryExpress/AddressUpdateViewController.swift, Examples/GroceryExpress/ConnectionViewController.swift, Examples/GroceryExpress/DisplayViewController.swift, Examples/GroceryExpress/Main.storyboard, IFTTT SDK/Array+Helpers.swift, IFTTT SDK/RegionsMonitor.swift, IFTTT SDK/URLSession+JSONTask.swift
- Fixing a bug where regions with duplicate identifiers but with different lat/lng weren't getting properly un-registered and registered with the system. 
- Adding views to grocery express to update address if skip config is set to true.
=> Region registration fixes

Examples/GroceryExpress/Main.storyboard, Examples/GroceryExpress/Settings.swift, Examples/GroceryExpress/SettingsViewController.swift, IFTTT SDK/ConnectButtonController+Public.swift, IFTTT SDK/Connection+Parsing.swift, IFTTT SDK/Connection+Storage.swift, IFTTT SDK/ConnectionsRegistry.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/LocationService.swift, IFTTT SDK/SynchronizationScheduler.swift, Location.md, SDKHostAppTests/ConnectionsRegistryTests.swift
Adding public methods to `ConnectButtonController` to assist in turning geofences for a connection on/off. The toggle will only work if the connection is enabled.
=> Adding SDK level toggle for connection geofences

IFTTT SDK/EventPublisher.swift, SDKHostAppTests/EventPublisherTests.swift, SDKHostAppTests/LocationServiceTests.swift
Fixing tests and adding dispatch queue to separate subscriber map accesses and subscriber closure execution
=> Event publisher updates

Examples/GroceryExpress/AppDelegate.swift, IFTTT SDK/ConnectButton+Constants.swift, IFTTT SDK/ConnectButtonController+Public.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/SynchronizationScheduler.swift, Location.md, SDKHostApp/AppDelegate.swift
Documentation will be updated.
=> Adding hooks that can be used to execute code when the system runs a background process

IFTTT SDK/ConnectButtonController.swift, IFTTT SDK/EventPublisher.swift, IFTTT SDK/SynchronizationScheduler.swift
- Fixing crash due to an attributed string replace not checking index not found. 
- Fixing notification observers not being properly removed in some code paths
=> Localization crash fix and notification observer cleanup fix

Examples/GroceryExpress/AppDelegate.swift, Examples/GroceryExpress/ConnectionCredentials.swift, Examples/GroceryExpress/SettingsViewController.swift, IFTTT SDK.xcodeproj/project.pbxproj, IFTTT SDK/ConnectButtonController+Public.swift, IFTTT SDK/ConnectionsSynchronizer.swift, IFTTT SDK/SynchronizationManager.swift, IFTTT SDK/SynchronizationScheduler.swift, SDKHostAppTests/SynchronizationSchedulerTests.swift
- Updating event registration to occur on start/stop of the scheduler.
- Updating scheduler unit tests
=> Event registration fixes
